version: "3.9"

services:
    # web:
    #     build: ./stock_helper
    #     container_name: web
    #     ports:
    #         - 8000:8000
    #     depends_on:
    #         - db
    db:
        image: postgres:15.2
        container_name: postgres_db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: jason
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: StockHelper
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: jason890088@gmail.com
            PGADMIN_DEFAULT_PASSWORD: jason
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    postgres_data:
    pgadmin-data:
